-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 20:46:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema colegio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colegio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colegio` DEFAULT CHARACTER SET utf8 ;
USE `colegio` ;

-- -----------------------------------------------------
-- Table `colegio`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `complemento` VARCHAR(25) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `fone` VARCHAR(13) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idaluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`turmas` (
  `idturmas` INT NOT NULL AUTO_INCREMENT,
  `turma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idturmas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`matriculas` (
  `idmatrticulas` INT NOT NULL AUTO_INCREMENT,
  `aluno_idaluno` INT NOT NULL,
  `turmas_idturmas` INT NOT NULL,
  `mensalidade` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NULL,
  `dtinicio` DATE NOT NULL,
  `dtfim` DATE NOT NULL,
  PRIMARY KEY (`idmatrticulas`),
  INDEX `fk_matrticulas_aluno_idx` (`aluno_idaluno` ASC) ,
  INDEX `fk_matrticulas_turmas1_idx` (`turmas_idturmas` ASC) ,
  CONSTRAINT `fk_matrticulas_aluno`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `colegio`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matrticulas_turmas1`
    FOREIGN KEY (`turmas_idturmas`)
    REFERENCES `colegio`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`materias` (
  `idmaterias` INT NOT NULL AUTO_INCREMENT,
  `materia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmaterias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`professor` (
  `idprofessor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `fone` VARCHAR(13) NOT NULL,
  `materias_idmaterias` INT NOT NULL,
  PRIMARY KEY (`idprofessor`),
  INDEX `fk_professor_materias1_idx` (`materias_idmaterias` ASC) ,
  CONSTRAINT `fk_professor_materias1`
    FOREIGN KEY (`materias_idmaterias`)
    REFERENCES `colegio`.`materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colegio`.`grade` (
  `materias_idmaterias` INT NOT NULL,
  `turmas_idturmas` INT NOT NULL,
  PRIMARY KEY (`materias_idmaterias`, `turmas_idturmas`),
  INDEX `fk_materias_has_turmas_turmas1_idx` (`turmas_idturmas` ASC) ,
  INDEX `fk_materias_has_turmas_materias1_idx` (`materias_idmaterias` ASC) ,
  CONSTRAINT `fk_materias_has_turmas_materias1`
    FOREIGN KEY (`materias_idmaterias`)
    REFERENCES `colegio`.`materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materias_has_turmas_turmas1`
    FOREIGN KEY (`turmas_idturmas`)
    REFERENCES `colegio`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
